#include <stdio.h>
#include <stdint.h>
#include "hw_info.h"
#include "command.h"

// Master umbrella header generated by Python tool
#include "fpga_design_config/fpga_design_config.h"

// Bit offsets defined in CONFIGURED_PERIPHERALS register XML
#define PERIPH_EMMC_BIT      (1U << 0)
#define PERIPH_SD_SDIO_BIT   (1U << 1)
#define PERIPH_USB_BIT       (1U << 2)
#define PERIPH_MAC0_BIT      (1U << 3)
#define PERIPH_MAC1_BIT      (1U << 4)
#define PERIPH_QSPI_BIT      (1U << 5)
#define PERIPH_SPI0_BIT      (1U << 6)
#define PERIPH_SPI1_BIT      (1U << 7)
#define PERIPH_MMUART0_BIT   (1U << 8)
#define PERIPH_MMUART1_BIT   (1U << 9)
#define PERIPH_MMUART2_BIT   (1U << 10)
#define PERIPH_MMUART3_BIT   (1U << 11)
#define PERIPH_MMUART4_BIT   (1U << 12)
#define PERIPH_I2C0_BIT      (1U << 13)
#define PERIPH_I2C1_BIT      (1U << 14)
#define PERIPH_CAN0_BIT      (1U << 15)
#define PERIPH_CAN1_BIT      (1U << 16)
#define PERIPH_GPIO0_BIT     (1U << 17)
#define PERIPH_GPIO1_BIT     (1U << 18)
#define PERIPH_GPIO2_BIT     (1U << 19)

void show_hw_info(void)
{
    printf("==================================================\n");
    printf("        PolarFire SoC Hardware Description        \n");
    printf("==================================================\n");

    // 1. Design Information
    printf("  [Design Information]\n");
    printf("    Target Part       : MPFS095T (FCSG325)\n");
    printf("    Design Name       : MPFS_DISCOVERY_KIT_MSS\n");
    printf("    Libero Version    : 2023.1\n\n");

    // 2. Dynamic Clocks Information (Read from XML generated macros)
    printf("  [System Clocks]\n");

#ifdef LIBERO_SETTING_MSS_COREPLEX_CPU_CLK
    printf("    CPU Coreplex Clock: %lu MHz (%lu Hz)\n",
           (unsigned long)(LIBERO_SETTING_MSS_COREPLEX_CPU_CLK / 1000000UL),
           (unsigned long)LIBERO_SETTING_MSS_COREPLEX_CPU_CLK);
#endif

#ifdef LIBERO_SETTING_MSS_SYSTEM_CLK
    printf("    System Clock      : %lu MHz (%lu Hz)\n",
           (unsigned long)(LIBERO_SETTING_MSS_SYSTEM_CLK / 1000000UL),
           (unsigned long)LIBERO_SETTING_MSS_SYSTEM_CLK);
#endif

#ifdef LIBERO_SETTING_MSS_AXI_CLK
    printf("    AXI Bus Clock     : %lu MHz (%lu Hz)\n",
           (unsigned long)(LIBERO_SETTING_MSS_AXI_CLK / 1000000UL),
           (unsigned long)LIBERO_SETTING_MSS_AXI_CLK);
#endif

#ifdef LIBERO_SETTING_MSS_APB_AHB_CLK
    printf("    APB/AHB Bus Clock : %lu MHz (%lu Hz)\n",
           (unsigned long)(LIBERO_SETTING_MSS_APB_AHB_CLK / 1000000UL),
           (unsigned long)LIBERO_SETTING_MSS_APB_AHB_CLK);
#endif

#ifdef LIBERO_SETTING_DDR_CLK
    printf("    DDR PHY Rate      : %lu MT/s (%lu Hz)\n\n",
           (unsigned long)(LIBERO_SETTING_DDR_CLK / 1000000UL),
           (unsigned long)LIBERO_SETTING_DDR_CLK);
#endif

    // 3. Memory Map Allocation
    printf("  [Memory Map]\n");
    printf("    Reset Vector      : 0x20220000 (Harts 0-4)\n");
    printf("    LIM Memory        : 0x08000000 - 0x081FFFFF (2MB)\n");
    printf("    DDR 32-bit Cache  : 0x80000000 - 0x800FFFFF (1MB)\n");
    printf("    DDR 32-bit NonCache: 0xC0000000 - 0xC00FFFFF (1MB)\n");
    printf("    DDR 64-bit Cache  : 0x1000000000 - 0x10000FFFFF\n");
    printf("    DDR 64-bit NonCache: 0x1400000000 - 0x14000FFFFF\n\n");

    // 4. Configured Active Peripherals
    printf("  [Configured MSS Peripherals]\n    Active: ");

#ifdef LIBERO_SETTING_CONFIGURED_PERIPHERALS
    uint32_t mask = LIBERO_SETTING_CONFIGURED_PERIPHERALS;

    if (mask & PERIPH_EMMC_BIT)    printf("eMMC ");
    if (mask & PERIPH_SD_SDIO_BIT) printf("SD/SDIO ");
    if (mask & PERIPH_USB_BIT)     printf("USB ");
    if (mask & PERIPH_MAC0_BIT)    printf("GEM0 ");
    if (mask & PERIPH_MAC1_BIT)    printf("GEM1 ");
    if (mask & PERIPH_QSPI_BIT)    printf("QSPI ");
    if (mask & PERIPH_SPI0_BIT)    printf("SPI0 ");
    if (mask & PERIPH_SPI1_BIT)    printf("SPI1 ");
    if (mask & PERIPH_MMUART0_BIT) printf("MMUART0 ");
    if (mask & PERIPH_MMUART1_BIT) printf("MMUART1 ");
    if (mask & PERIPH_MMUART2_BIT) printf("MMUART2 ");
    if (mask & PERIPH_MMUART3_BIT) printf("MMUART3 ");
    if (mask & PERIPH_MMUART4_BIT) printf("MMUART4 ");
    if (mask & PERIPH_I2C0_BIT)    printf("I2C0 ");
    if (mask & PERIPH_I2C1_BIT)    printf("I2C1 ");
    if (mask & PERIPH_CAN0_BIT)    printf("CAN0 ");
    if (mask & PERIPH_CAN1_BIT)    printf("CAN1 ");
    if (mask & PERIPH_GPIO0_BIT)   printf("GPIO0 ");
    if (mask & PERIPH_GPIO1_BIT)   printf("GPIO1 ");
    if (mask & PERIPH_GPIO2_BIT)   printf("GPIO2 ");
#else
    printf("None (LIBERO_SETTING_CONFIGURED_PERIPHERALS not defined)");
#endif

    printf("\n==================================================\n\n");
}

void hw_info_handler(int nb_params, char **params)
{
    (void)nb_params;
    (void)params;
    show_hw_info();
}